<?php

namespace CoffeeShopBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return
     */
    public function findProducts()
    {
        return $this->createQueryBuilder("categories")
            ->join("categories.products", "products")
            ->addSelect("products")->getQuery()->getResult();
    }

    public function getNonEmptyCategories()
    {
        return $this->createQueryBuilder("product_category")
            ->join("product_category.products", "products")
            ->addSelect("products")
            ->orderBy("product_category.name", "ASC")
            ->getQuery()
            ->execute();
    }

    /**
     * @return QueryBuilder
     */
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("product_category")
            ->join("product_category.products", "products")
            ->addSelect("products");
    }
}
