<?php

namespace CoffeeShopBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * OrderProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("products_order");
    }
}
