<?php

namespace CoffeeShopBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("product")
            ->where("product.quantity > 0");
    }

    public function selectByIdAsc()
    {
        return $this->createQueryBuilder("product")
            ->select('product')
            ->orderBy('product.id', 'ASC');

    }


}
