<?php

namespace CoffeeShopBundle\Repository;

use CoffeeShopBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("product")
            ->where("product.quantity > 0");
    }

    public function selectByIdAsc()
    {
        return $this->createQueryBuilder("product")
            ->select('product')
            ->orderBy('product.id', 'ASC');

    }

    public function selectNewProduct()
    {

        $q = $this->createQueryBuilder('product')
            ->select('product')
            ->orderBy('product.addedOn', 'DESC')
            ->setMaxResults(6)
            ->getQuery();

        return $q->getResult();
    }

    public function findAllByCategoryQueryBuilder($id)
    {
        $q = $this->createQueryBuilder("product")
            ->leftJoin("product.category", "c")
            ->where("product.quantity > 0")
            ->andWhere("c.id = :id")
            ->setParameter("id", $id)
            ->getQuery();

        return $q->getResult();
    }


}
