<?php

namespace CoffeeShopBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectByIdAsc()
    {
        return $this->createQueryBuilder("user")
            ->select('user')
            ->orderBy('user.id', 'ASC');



    }
}
